name: emiamily History

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run GMMTV History
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_TO: ${{ secrets.GMAIL_TO }}
        run: |
          python gmmtv_history.py
